//! PDF parsing module.

pub mod backend;
pub mod bidi;
mod clip;
pub mod cmap_table;
mod core14;
#[rustfmt::skip] // generated by scripts/gen_core14_metrics.py
mod core14_data;
mod dedup;
pub(crate) mod encoding;
pub(crate) mod font;
mod form_xobject;
pub(crate) mod glyph_metrics;
mod lattice;
mod layout;
mod ocr_gate;
mod options;
mod pdf_parser;
pub(crate) mod png_encode;
pub(crate) mod predefined_cmap;
#[cfg(feature = "raster")]
pub mod raster;
#[cfg(feature = "raster")]
mod raster_text;
pub mod raw;
pub(crate) mod sanitize;
pub mod stream;
mod table_detector;
#[cfg(test)]
pub(crate) mod test_pdf;
mod text_string;
#[cfg(feature = "raster")]
mod type1;
mod vector_graphics;
pub mod xycut;

pub use layout::{
    BlockType, FontStatistics, LayoutAnalyzer, PageFacts, PageOpCounts, TextBlock, TextLine,
    TextSpan,
};
pub use options::{ErrorMode, ParseOptions};
pub use pdf_parser::PdfParser;
pub use stream::{PageStreamOptions, ParseEvent};
pub use table_detector::{DetectedTable, TableDetector, TableDetectorConfig, TableRowData};
