"""Generate src/parser/agl_data.rs — the Adobe Glyph List, glyph name -> Unicode.

    python scripts/gen_agl.py <glyphlist.txt>

glyphlist.txt: https://github.com/adobe-type-tools/agl-aglfn (the full AGL, not AGLFN).
A name the list maps to a sequence of code points keeps the first, as glyph names are
resolved to one character each. Names are sorted by their bytes, for binary search. The
list's copyright notice, conditions and disclaimer are carried into the generated file
verbatim, as its license requires.
"""

import pathlib
import sys


def main() -> int:
    source = pathlib.Path(sys.argv[1])
    lines = source.read_text(encoding="utf-8").splitlines()

    # The notice: the comment block between the first two rulers.
    rulers = [i for i, line in enumerate(lines) if line.startswith("# ---")]
    notice = [line[2:] if line.startswith("# ") else "" for line in lines[rulers[0] + 1 : rulers[1]]]

    entries = {}
    for line in lines:
        if not line.strip() or line.startswith("#"):
            continue
        name, codes = line.split(";")
        entries.setdefault(name, int(codes.split()[0], 16))
    names = sorted(entries, key=lambda n: n.encode())

    out = [
        "//! The Adobe Glyph List: glyph name -> Unicode.",
        "//!",
        "//! GENERATED by `scripts/gen_agl.py` from glyphlist.txt (Adobe Glyph List, table",
        "//! version 2.0) — do not edit by hand. A name the list maps to a sequence of code points",
        "//! keeps the first. Sorted by name, for binary search.",
        "//!",
        "//! The list is distributed under the following notice, reproduced as it requires:",
        "//!",
    ]
    out += [f"//! {line}".rstrip() for line in notice]
    out += ["", f"pub(crate) static AGL: [(&str, char); {len(names)}] = ["]
    for name in names:
        out.append(f'    ("{name}", \'\\u{{{entries[name]:04X}}}\'),')
    out.append("];")
    target = pathlib.Path(__file__).resolve().parent.parent / "src" / "parser" / "agl_data.rs"
    target.write_text("\n".join(out) + "\n", encoding="utf-8", newline="\n")
    print(f"{target}: {len(names)} names")
    return 0


if __name__ == "__main__":
    sys.exit(main())
