#!/usr/bin/env python3
"""Generate src/parser/core14_data.rs from the Adobe Core14 AFM files.

The 14 standard Type 1 fonts may be used without embedding and, before PDF 1.5,
without a /Widths array (ISO 32000-1 §9.6.2.2). A reader then needs the fonts'
own metrics. This script reads the AFM files and the Adobe Glyph List and writes
the advance widths as Rust constants.

Usage:
    python scripts/gen_core14_metrics.py <dir-with-afm-files> <glyphlist.txt>

Sources (public):
    AFM files      https://github.com/apache/pdfbox/tree/trunk/pdfbox/src/main/resources/org/apache/pdfbox/resources/afm
    glyphlist.txt  https://github.com/adobe-type-tools/agl-aglfn
"""

import pathlib
import re
import sys

LATIN = [
    ("COURIER", "Courier"),
    ("COURIER_BOLD", "Courier-Bold"),
    ("COURIER_OBLIQUE", "Courier-Oblique"),
    ("COURIER_BOLD_OBLIQUE", "Courier-BoldOblique"),
    ("HELVETICA", "Helvetica"),
    ("HELVETICA_BOLD", "Helvetica-Bold"),
    ("HELVETICA_OBLIQUE", "Helvetica-Oblique"),
    ("HELVETICA_BOLD_OBLIQUE", "Helvetica-BoldOblique"),
    ("TIMES_ROMAN", "Times-Roman"),
    ("TIMES_BOLD", "Times-Bold"),
    ("TIMES_ITALIC", "Times-Italic"),
    ("TIMES_BOLD_ITALIC", "Times-BoldItalic"),
]
SYMBOLIC = [("SYMBOL", "Symbol"), ("ZAPF_DINGBATS", "ZapfDingbats")]

BACKSLASH = chr(0x5C)
CHAR_METRIC =re.compile(r"^C (-?\d+) ; WX (\d+) ; N (\S+) ;")


def read_afm(path):
    """[(code in the font's built-in encoding, width, glyph name)]"""
    out = []
    for line in path.read_text(encoding="latin-1").splitlines():
        m = CHAR_METRIC.match(line)
        if m:
            out.append((int(m.group(1)), int(m.group(2)), m.group(3)))
    if not out:
        sys.exit(f"no character metrics in {path}")
    return out


def read_agl(path):
    agl = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("#") or not line.strip():
            continue
        name, codes = line.split(";")
        agl.setdefault(name, int(codes.split()[0], 16))
    return agl


def chunks(values, per_line):
    for i in range(0, len(values), per_line):
        yield ", ".join(values[i : i + per_line])


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    afm_dir, agl = pathlib.Path(sys.argv[1]), read_agl(pathlib.Path(sys.argv[2]))

    latin = {const: {name: w for _, w, name in read_afm(afm_dir / f"{font}.afm")} for const, font in LATIN}
    glyphs = set(next(iter(latin.values())))
    for const, widths in latin.items():
        if set(widths) != glyphs:
            sys.exit(f"{const}: glyph set differs from the other Latin fonts")
    by_char = sorted(glyphs, key=lambda n: agl[n])
    chars = [agl[n] for n in by_char]
    if len(set(chars)) != len(chars):
        sys.exit("two Latin glyphs map to the same code point")

    out = [
        "//! Advance widths of the 14 standard Type 1 fonts.",
        "//!",
        "//! GENERATED by `scripts/gen_core14_metrics.py` from the Adobe Core14 AFM files",
        "//! (AFM 4.1) — do not edit by hand. Widths are in thousandths of text space.",
        "//!",
        "//! The metrics are Copyright (c) 1985, 1987, 1989, 1990, 1991, 1992, 1993, 1997",
        "//! Adobe Systems Incorporated. Adobe permits the AFM files to be used, copied and",
        "//! distributed for any purpose without charge, with or without modification,",
        "//! provided the copyright notices are retained and modifications are noted. This",
        "//! file is a modification: only the advance widths (`WX`) are kept, re-indexed by",
        "//! Unicode code point (Latin fonts) or by built-in encoding code (Symbol,",
        "//! ZapfDingbats).",
        "",
        f"/// The glyphs every Latin standard font covers, as Unicode code points, sorted.",
        f"pub(crate) const LATIN_CHARS: [char; {len(chars)}] = [",
    ]
    out += [f"    {line}," for line in chunks([f"'{BACKSLASH}u{{{c:04X}}}'" for c in chars], 8)]
    out.append("];")
    for const, font in LATIN:
        out += ["", f"/// `{font}`, indexed like [`LATIN_CHARS`].", f"pub(crate) static {const}: [u16; {len(chars)}] = ["]
        out += [f"    {line}," for line in chunks([str(latin[const][n]) for n in by_char], 16)]
        out.append("];")
    for const, font in SYMBOLIC:
        table = [0] * 256
        for code, width, _ in read_afm(afm_dir / f"{font}.afm"):
            if 0 <= code <= 255:
                table[code] = width
        out += ["", f"/// `{font}`, indexed by code in its built-in encoding (0 = no glyph).", f"pub(crate) static {const}: [u16; 256] = ["]
        out += [f"    {line}," for line in chunks([str(w) for w in table], 16)]
        out.append("];")

    target = pathlib.Path(__file__).resolve().parent.parent / "src" / "parser" / "core14_data.rs"
    target.write_text("\n".join(out) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {target}")


if __name__ == "__main__":
    main()
