"""Generate src/parser/cff_strings.rs — the 391 CFF standard strings.

    python scripts/gen_cff_strings.py

The strings are those of Adobe Technical Note #5176 (The Compact Font Format
Specification), Appendix A: string IDs 0-390, which a CFF font uses without storing them.
The list is taken from fontTools (`fontTools.cffLib.cffStandardStrings`), which
reproduces the appendix.
"""

import pathlib
import sys

from fontTools.cffLib import cffStandardStrings


def main() -> int:
    strings = list(cffStandardStrings)
    assert len(strings) == 391, len(strings)
    out = [
        "//! The CFF standard strings: string IDs 0-390 (Adobe Technical Note #5176, Appendix A).",
        "//!",
        "//! GENERATED by `scripts/gen_cff_strings.py` — do not edit by hand.",
        "",
        f"pub(crate) static STANDARD_STRINGS: [&str; {len(strings)}] = [",
    ]
    out += [f'    "{s}",' for s in strings]
    out.append("];")
    target = pathlib.Path(__file__).resolve().parent.parent / "src" / "parser" / "cff_strings.rs"
    target.write_text("\n".join(out) + "\n", encoding="utf-8", newline="\n")
    print(f"{target}: {len(strings)} strings")
    return 0


if __name__ == "__main__":
    sys.exit(main())
